//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuul.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zuul.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password for User Account, the new password was the same as the old password..
        /// </summary>
        public static string ChangePasswordNewPasswordMustNotMatchOld {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordMustNotMatchOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password for User Account, the old password specified was incorrect..
        /// </summary>
        public static string ChangePasswordOldPasswordNotCorrect {
            get {
                return ResourceManager.GetString("ChangePasswordOldPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password for User Account, the supplied email address did not match an existing account: {0}.
        /// </summary>
        public static string ChangePasswordUserAccountEmailAddressNotFound {
            get {
                return ResourceManager.GetString("ChangePasswordUserAccountEmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, the message must be between 3 and 4000 characters..
        /// </summary>
        public static string CreatePostMessageError {
            get {
                return ResourceManager.GetString("CreatePostMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, you must be logged in to perform this action..
        /// </summary>
        public static string CreatePostMustBeLoggedIn {
            get {
                return ResourceManager.GetString("CreatePostMustBeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, the suppplied parent Post was not found..
        /// </summary>
        public static string CreatePostParentPostNotFound {
            get {
                return ResourceManager.GetString("CreatePostParentPostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, the supplied Thread was not found..
        /// </summary>
        public static string CreatePostThreadNotFound {
            get {
                return ResourceManager.GetString("CreatePostThreadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, the subject must be between 3 and 200 characters..
        /// </summary>
        public static string CreatePostTitleError {
            get {
                return ResourceManager.GetString("CreatePostTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Post, the User Account could not be found..
        /// </summary>
        public static string CreatePostUserAccountNotFound {
            get {
                return ResourceManager.GetString("CreatePostUserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Thread, the message must be between 3 and 4000 characters..
        /// </summary>
        public static string CreateThreadMessageError {
            get {
                return ResourceManager.GetString("CreateThreadMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Thread, you must be logged in to perform this action..
        /// </summary>
        public static string CreateThreadMustBeLoggedIn {
            get {
                return ResourceManager.GetString("CreateThreadMustBeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Thread, the subject must be between 3 and 200 characters..
        /// </summary>
        public static string CreateThreadTitleError {
            get {
                return ResourceManager.GetString("CreateThreadTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Thread, the User Account could not be found..
        /// </summary>
        public static string CreateThreadUserAccountNotFound {
            get {
                return ResourceManager.GetString("CreateThreadUserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, an account already exists with the specified email address: {0}.
        /// </summary>
        public static string CreateUserAccountEmailAddressDuplicate {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, the supplied email address must contain an @ symbol: {0}.
        /// </summary>
        public static string CreateUserAccountEmailAddressNoAtSymbol {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressNoAtSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, the supplied email address must contain a . symbol: {0}.
        /// </summary>
        public static string CreateUserAccountEmailAddressNoDotSymbol {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressNoDotSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, the supplied email address was too long. An email address must be 256 characters or less..
        /// </summary>
        public static string CreateUserAccountEmailAddressTooLong {
            get {
                return ResourceManager.GetString("CreateUserAccountEmailAddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, no email address was supplied..
        /// </summary>
        public static string CreateUserAccountEmptyEmailAddress {
            get {
                return ResourceManager.GetString("CreateUserAccountEmptyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, an account already exists with the specified username: {0}.
        /// </summary>
        public static string CreateUserAccountEmptyUsername {
            get {
                return ResourceManager.GetString("CreateUserAccountEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, a password must be supplied..
        /// </summary>
        public static string CreateUserAccountPasswordMustBeSupplied {
            get {
                return ResourceManager.GetString("CreateUserAccountPasswordMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, the supplied passwords much match..
        /// </summary>
        public static string CreateUserAccountPasswordsMustMatch {
            get {
                return ResourceManager.GetString("CreateUserAccountPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, an account already exists with the specified username: {0}.
        /// </summary>
        public static string CreateUserAccountUsernameDuplicate {
            get {
                return ResourceManager.GetString("CreateUserAccountUsernameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create User Account, the supplied username was too long. A username must be 30 characters or less..
        /// </summary>
        public static string CreateUserAccountUsernameTooLong {
            get {
                return ResourceManager.GetString("CreateUserAccountUsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, a new password must be supplied..
        /// </summary>
        public static string UpdatePasswordPasswordMustBeSupplied {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordMustBeSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, the supplied passwords must match..
        /// </summary>
        public static string UpdatePasswordPasswordsMustMatch {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, the supplied password must be at least 8 characters in length..
        /// </summary>
        public static string UpdatePasswordPasswordTooShort {
            get {
                return ResourceManager.GetString("UpdatePasswordPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, the authentication code has expired. Please request another code to reset your password..
        /// </summary>
        public static string UpdatePasswordTokenExpired {
            get {
                return ResourceManager.GetString("UpdatePasswordTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, the authentication code was incorrect..
        /// </summary>
        public static string UpdatePasswordTokenIncorrect {
            get {
                return ResourceManager.GetString("UpdatePasswordTokenIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password, the supplied email address did not match an existing account..
        /// </summary>
        public static string UpdatePasswordUserAccountNotFound {
            get {
                return ResourceManager.GetString("UpdatePasswordUserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate User Account, the account is not yet active. Please click on the link sent to {0} to activate your account..
        /// </summary>
        public static string UserAccountNotActivated {
            get {
                return ResourceManager.GetString("UserAccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password must contain at least one alphabet character (A-Z)..
        /// </summary>
        public static string UserAccountPasswordNoAlphabetCharacters {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoAlphabetCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password must contain at least one non alphanumeric character (for example punctuation or mathematical symbols)..
        /// </summary>
        public static string UserAccountPasswordNoNonAlphanumericCharacter {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoNonAlphanumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password must contain at least one numeric character (0-9)..
        /// </summary>
        public static string UserAccountPasswordNoNumericCharacter {
            get {
                return ResourceManager.GetString("UserAccountPasswordNoNumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password must be 20 character or less in length..
        /// </summary>
        public static string UserAccountPasswordTooLong {
            get {
                return ResourceManager.GetString("UserAccountPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied password must be at least 8 characters in length..
        /// </summary>
        public static string UserAccountPasswordTooShort {
            get {
                return ResourceManager.GetString("UserAccountPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified User Account..
        /// </summary>
        public static string UserAccountUserIdNotFound {
            get {
                return ResourceManager.GetString("UserAccountUserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate User Account, the supplied email address did not match an existing account: {0}.
        /// </summary>
        public static string ValidateUserAccountEmailNotFound {
            get {
                return ResourceManager.GetString("ValidateUserAccountEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate User Account, the supplied username did not match an existing account: {0}.
        /// </summary>
        public static string ValidateUsernameNotFound {
            get {
                return ResourceManager.GetString("ValidateUsernameNotFound", resourceCulture);
            }
        }
    }
}
